apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    type: back
spec:
  replicas: 2
  template:
    metadata:
      name: app-pod
      labels:
        type: back-pod
    spec:
      containers:
       - name: app-c
         image: httpd
         ports:
          - containerPort: 80
  selector:
      matchLabels:
          type: back-pod
---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
  labels:
    type: app-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
  selector:
     type: back-pod

